services:
    # Stats listener
    stats.listener:
        class: StatsBundle\EventListener\StatsListener
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: "kernel.event_subscriber" }
