services:
    # Stats manager
    stats.manager:
        class: StatsBundle\Manager\StatsManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@weapon.registry"

    # Stats listener
    stats.listener:
        class: StatsBundle\EventListener\StatsListener
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: "kernel.event_subscriber" }
