jms_translation:
    configs:
        app:
            dirs: ["%kernel.root_dir%", "%kernel.root_dir%/../src"]
            output_dir: "%kernel.root_dir%/Resources/translations"
            ignored_domains: [FOSUserBundle]
            excluded_names: ["User.php"]

bazinga_js_translation:
    default_domain: messages
    locale_fallback: "en"
    active_locales:
            - en
