security:
    encoders:
        UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main_provider:
            entity: { class: UserBundle\Entity\User }
        api_provider:
            id: api.user_provider

    firewalls:
        # disables authentication for assets and the profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            provider: api_provider
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: api.key_authenticator

        main:
            provider: main_provider
            pattern: ^/
            anonymous: ~
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH, parameter: _user }
            logout_on_user_change: true
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                post_only: true
                use_referer: true
                remember_me: true
            logout:
                path: fos_user_security_logout
                target: /
            remember_me:
                name: "%session_name%-remember"
                secret: "%secret%"
                secure: "%use_ssl%"
                lifetime: 604800 # 1 week
                path: /
                user_provider: main_provider

    access_control:
        - { path: ^/api, role: ROLE_API }
        - { path: ^/translations$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manifest, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
