<?php

namespace NotificationBundle\Repository;

/**
 * SMSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SMSRepository extends \Doctrine\ORM\EntityRepository
{
}
